In [1]:
import pandas as pd
from datetime import timedelta

# Read the CSV file
data_15 = pd.read_csv('travel_times_15_17.csv')

# Convert departure_time to datetime
data_15['departure_time'] = pd.to_datetime(data_15['departure_time'])

data_15 = data_15[data_15['departure_time'] != '2025-12-18 17:00:00']
# Create an empty list to store the new rows
new_rows = []

# For each unique timestamp in the original data
unique_times = sorted(data_15['departure_time'].unique())

for time in unique_times:
    # Get all rows for this timestamp
    rows_at_time = data_15[data_15['departure_time'] == time]
    
    # Add the original rows
    new_rows.append(rows_at_time)
    
    # Create duplicate rows with +10 minutes
    rows_plus_10 = rows_at_time.copy()
    rows_plus_10['departure_time'] = time + timedelta(minutes=10)
    new_rows.append(rows_plus_10)

# Concatenate all rows
result_df_15 = pd.concat(new_rows, ignore_index=True)

# Sort by departure_time and origin_station_id for better organization
result_df_15 = result_df_15.sort_values(['departure_time', 'origin_station_id']).reset_index(drop=True)

# Save to new CSV file
result_df_15.to_csv('interpolated_data_8.csv', index=False)

print(f"Original data shape: {data_15.shape}")
print(f"New data shape: {result_df_15.shape}")
print(f"\nFirst few rows:")
print(result_df_15.head(20))

Original data shape: (5684, 15)
New data shape: (11368, 15)

First few rows:
        departure_time  origin_station_id         origin_name  origin_lat  \
0  2026-02-12 15:00:00            8504622  Fribourg, Bellevue   46.810927   
1  2026-02-12 15:00:00            8504622  Fribourg, Bellevue   46.810927   
2  2026-02-12 15:00:00            8504622  Fribourg, Bellevue   46.810927   
3  2026-02-12 15:00:00            8504622  Fribourg, Bellevue   46.810927   
4  2026-02-12 15:00:00            8504622  Fribourg, Bellevue   46.810927   
5  2026-02-12 15:00:00            8504622  Fribourg, Bellevue   46.810927   
6  2026-02-12 15:00:00            8504622  Fribourg, Bellevue   46.810927   
7  2026-02-12 15:00:00            8504622  Fribourg, Bellevue   46.810927   
8  2026-02-12 15:00:00            8504622  Fribourg, Bellevue   46.810927   
9  2026-02-12 15:00:00            8504622  Fribourg, Bellevue   46.810927   
10 2026-02-12 15:00:00            8504622  Fribourg, Bellevue   46.810927   

In [2]:
import pandas as pd
from datetime import timedelta

# Read the CSV file
data_19 = pd.read_csv('travel_times_19_21.csv')

# Convert departure_time to datetime
data_19['departure_time'] = pd.to_datetime(data_19['departure_time'])


# Create an empty list to store the new rows
new_rows = []

# For each unique timestamp in the original data
unique_times = sorted(data_19['departure_time'].unique())

for time in unique_times:
    # Get all rows for this timestamp
    rows_at_time = data_19[data_19['departure_time'] == time]
    
    # Add the original rows
    new_rows.append(rows_at_time)
    
    # Create duplicate rows with +10 minutes
    rows_plus_10 = rows_at_time.copy()
    rows_plus_10['departure_time'] = time + timedelta(minutes=10)
    new_rows.append(rows_plus_10)

# Concatenate all rows
result_df_19 = pd.concat(new_rows, ignore_index=True)

# Sort by departure_time and origin_station_id for better organization
result_df_19 = result_df_19.sort_values(['departure_time', 'origin_station_id']).reset_index(drop=True)


result_df_19 = result_df_19[result_df_19['departure_time'] != '2025-12-18 21:10:00']

# Save to new CSV file
result_df_19.to_csv('interpolated_data.csv', index=False)
print(f"Original data shape: {data_19.shape}")
print(f"New data shape: {result_df_19.shape}")
print(f"\nFirst few rows:")
print(result_df_19.head(20))

Original data shape: (5684, 15)
New data shape: (11368, 15)

First few rows:
        departure_time  origin_station_id         origin_name  origin_lat  \
0  2026-02-12 19:00:00            8504622  Fribourg, Bellevue   46.810927   
1  2026-02-12 19:00:00            8504622  Fribourg, Bellevue   46.810927   
2  2026-02-12 19:00:00            8504622  Fribourg, Bellevue   46.810927   
3  2026-02-12 19:00:00            8504622  Fribourg, Bellevue   46.810927   
4  2026-02-12 19:00:00            8504622  Fribourg, Bellevue   46.810927   
5  2026-02-12 19:00:00            8504622  Fribourg, Bellevue   46.810927   
6  2026-02-12 19:00:00            8504622  Fribourg, Bellevue   46.810927   
7  2026-02-12 19:00:00            8504622  Fribourg, Bellevue   46.810927   
8  2026-02-12 19:00:00            8504622  Fribourg, Bellevue   46.810927   
9  2026-02-12 19:00:00            8504622  Fribourg, Bellevue   46.810927   
10 2026-02-12 19:00:00            8504622  Fribourg, Bellevue   46.810927   

In [3]:
data_17 = pd.read_csv('travel_times_17_19.csv')
data_17['departure_time'] = pd.to_datetime(data_17['departure_time'])
result_df_17 = data_17[data_17['departure_time'] != '2025-12-18 19:00:00']
result_df_17.to_csv('interpolated_data_8.csv', index=False)

In [4]:
# Concatenate the three dataframes vertically
combined_df = pd.concat([result_df_15, result_df_17, result_df_19], ignore_index=True)

# Sort by departure_time and origin_station_id for better organization
combined_df = combined_df.sort_values(['departure_time', 'origin_station_id']).reset_index(drop=True)

# Save to new CSV file
combined_df.to_csv('combined_data_8.csv', index=False)

In [5]:
combined_df

,departure_time,origin_station_id,origin_name,origin_lat,origin_lon,dest_station_id,dest_name,dest_lat,dest_lon,distance_meters,duration_seconds,duration_minutes,duration_in_traffic_seconds,duration_in_traffic_minutes,status
0,2026-02-12 15:00:00,8504622,"Fribourg, Bellevue",46.810927,7.171933,8589141,"Fribourg, Chaley",46.806281,7.175601,876,121,2.02,144,2.40,OK
1,2026-02-12 15:00:00,8504622,"Fribourg, Bellevue",46.810927,7.171933,8589152,"Fribourg, Mon-Repos",46.806711,7.172136,593,81,1.35,88,1.47,OK
2,2026-02-12 15:00:00,8504622,"Fribourg, Bellevue",46.810927,7.171933,8589138,"Fribourg, Cité-Jardins",46.809385,7.170446,204,28,0.47,32,0.53,OK
3,2026-02-12 15:00:00,8504622,"Fribourg, Bellevue",46.810927,7.171933,8591766,"Fribourg, Boschung",46.811451,7.171016,147,24,0.40,27,0.45,OK
4,2026-02-12 15:00:00,8504622,"Fribourg, Bellevue",46.810927,7.171933,8587255,"Fribourg, Tilleul/Cathédrale",46.806090,7.161261,2921,331,5.52,364,6.07,OK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33287,2026-02-12 21:10:00,8592378,"Villars-sur-Glâne,Jean Paul II",46.803893,7.137545,8588858,"Fribourg, J. Vogt",46.798348,7.153271,2397,457,7.62,392,6.53,OK
33288,2026-02-12 21:10:00,8592378,"Villars-sur-Glâne,Jean Paul II",46.803893,7.137545,8589155,"Fribourg, Fries",46.800675,7.152251,2457,470,7.83,381,6.35,OK
33289,2026-02-12 21:10:00,8592378,"Villars-sur-Glâne,Jean Paul II",46.803893,7.137545,8588351,"Fribourg, Gambach",46.806306,7.151170,1590,292,4.87,267,4.45,OK
33290,2026-02-12 21:10:00,8592378,"Villars-sur-Glâne,Jean Paul II",46.803893,7.137545,8577820,"Fribourg, Vuille",46.809549,7.146039,2025,354,5.90,321,5.35,OK


In [6]:
print(combined_df)

           departure_time  origin_station_id                     origin_name  \
0     2026-02-12 15:00:00            8504622              Fribourg, Bellevue   
1     2026-02-12 15:00:00            8504622              Fribourg, Bellevue   
2     2026-02-12 15:00:00            8504622              Fribourg, Bellevue   
3     2026-02-12 15:00:00            8504622              Fribourg, Bellevue   
4     2026-02-12 15:00:00            8504622              Fribourg, Bellevue   
...                   ...                ...                             ...   
33287 2026-02-12 21:10:00            8592378  Villars-sur-Glâne,Jean Paul II   
33288 2026-02-12 21:10:00            8592378  Villars-sur-Glâne,Jean Paul II   
33289 2026-02-12 21:10:00            8592378  Villars-sur-Glâne,Jean Paul II   
33290 2026-02-12 21:10:00            8592378  Villars-sur-Glâne,Jean Paul II   
33291 2026-02-12 21:10:00            8592378  Villars-sur-Glâne,Jean Paul II   

       origin_lat  origin_lon  dest_sta

In [ ]:
import numpy as np
data = np.load('data/travel_time_all_zero.npy')
data

array([], shape=(29, 29, 0), dtype=float32)

In [13]:
import numpy as np


travel_time_matrix = np.zeros((29, 29, 36), dtype=np.float32)


np.save('data/travel_time_matrix.npy', travel_time_matrix)

print(f"Matrix shape: {travel_time_matrix.shape}")
print(f"Matrix dtype: {travel_time_matrix.dtype}")
print(f"All values are zero: {np.all(travel_time_matrix == 0)}")
print(f"\nMatrix saved to 'data/travel_time_matrix.npy'")

Matrix shape: (29, 29, 36)
Matrix dtype: float32
All values are zero: True

Matrix saved to 'data/travel_time_matrix.npy'


In [15]:
import pandas as pd
import numpy as np
import json

# Read the JSON file with station information
with open('data/stations.json', 'r', encoding='utf-8') as f:
    stations_data = json.load(f)

# Create a mapping from station_id to index
station_id_to_index = {station['station_id']: station['index'] 
                       for station in stations_data['stations']}

# Convert departure_time to datetime if not already
combined_df['departure_time'] = pd.to_datetime(combined_df['departure_time'])

# Get unique timestamps and sort them
unique_times = sorted(combined_df['departure_time'].unique())
print(f"Number of unique timestamps: {len(unique_times)}")
print(f"Time range: {unique_times[0]} to {unique_times[-1]}")


actual_date = unique_times[0].date()  
start_time = pd.to_datetime(f'{actual_date} 15:00:00')
end_time = pd.to_datetime(f'{actual_date} 21:00:00')

print(f"\nFiltering for date: {actual_date}")
print(f"Time range: {start_time} to {end_time}")

# Filter to only keep times from 15:00 to 21:00
filtered_times = [t for t in unique_times if start_time <= t < end_time]
print(f"\nFiltered timestamps: {len(filtered_times)}")
if filtered_times:
    print(f"First few: {filtered_times[:5]}")
    print(f"Last few: {filtered_times[-5:]}")

# Check if we have exactly 36 time slots
if len(filtered_times) != 36:
    print(f"\nWARNING: Expected 36 time slots but got {len(filtered_times)}")
    print("Note: You have 38 timestamps covering 15:00-21:10 (every 10 min would be 37 slots)")

# Initialize the 3D array - use 36 slots as intended
n_time_slots = 36  # Fixed size for consistency
travel_time_matrix = np.zeros((29, 29, n_time_slots), dtype=np.float32)

# Use only the first 36 time slots
filtered_times = filtered_times[:36]

# Fill the matrix with travel times
for time_idx, timestamp in enumerate(filtered_times):
    # Get all rows for this timestamp
    time_slice = combined_df[combined_df['departure_time'] == timestamp]
    
    for _, row in time_slice.iterrows():
        origin_id = str(row['origin_station_id'])
        dest_id = str(row['dest_station_id'])
        
        # Check if both stations are in our station mapping
        if origin_id in station_id_to_index and dest_id in station_id_to_index:
            origin_idx = station_id_to_index[origin_id]
            dest_idx = station_id_to_index[dest_id]
            
            # Use duration_in_traffic_minutes as the travel time
            travel_time = row['duration_in_traffic_minutes'] * 60
            
            # Store in the matrix
            travel_time_matrix[origin_idx, dest_idx, time_idx] = travel_time

# Save the numpy array
np.save('data/travel_time_matrix.npy', travel_time_matrix)

print(f"\n=== FINAL RESULTS ===")
print(f"Matrix shape: {travel_time_matrix.shape}")
print(f"Matrix dtype: {travel_time_matrix.dtype}")
print(f"\nSample values at time slot 0 (15:00):")
print(travel_time_matrix[:5, :5, 0])
print(f"\nNon-zero entries: {np.count_nonzero(travel_time_matrix)}")
print(f"Total entries: {travel_time_matrix.size}")
print(f"Percentage filled: {100 * np.count_nonzero(travel_time_matrix) / travel_time_matrix.size:.2f}%")

# Verify: check a specific route
print("\nVerification - Travel time from station 0 to station 1 across all time slots:")
print(travel_time_matrix[0, 1, :])

Number of unique timestamps: 38
Time range: 2026-02-12 15:00:00 to 2026-02-12 21:10:00

Filtering for date: 2026-02-12
Time range: 2026-02-12 15:00:00 to 2026-02-12 21:00:00

Filtered timestamps: 36
First few: [Timestamp('2026-02-12 15:00:00'), Timestamp('2026-02-12 15:10:00'), Timestamp('2026-02-12 15:20:00'), Timestamp('2026-02-12 15:30:00'), Timestamp('2026-02-12 15:40:00')]
Last few: [Timestamp('2026-02-12 20:10:00'), Timestamp('2026-02-12 20:20:00'), Timestamp('2026-02-12 20:30:00'), Timestamp('2026-02-12 20:40:00'), Timestamp('2026-02-12 20:50:00')]

=== FINAL RESULTS ===
Matrix shape: (29, 29, 36)
Matrix dtype: float32

Sample values at time slot 0 (15:00):
[[  0.   42.  117.  174.  505.8]
 [ 45.    0.   73.2 138.  462. ]
 [100.8  55.2   0.   63.  400.8]
 [162.  106.8  51.    0.  339. ]
 [498.  456.  400.8 346.2   0. ]]

Non-zero entries: 29232
Total entries: 30276
Percentage filled: 96.55%

Verification - Travel time from station 0 to station 1 across all time slots:
[42.  42. 

In [16]:
travel_time_matrix

array([[[  0. ,   0. ,   0. , ...,   0. ,   0. ,   0. ],
        [ 42. ,  42. ,  42. , ...,  36. ,  40.2,  40.2],
        [117. , 117. , 117. , ...,  85.8,  90. ,  90. ],
        ...,
        [633. , 633. , 648. , ..., 550.2, 556.2, 556.2],
        [535.2, 535.2, 549. , ..., 469.2, 477. , 477. ],
        [675. , 675. , 687. , ..., 594. , 601.2, 601.2]],

       [[ 45. ,  45. ,  45. , ...,  42. ,  43.2,  43.2],
        [  0. ,   0. ,   0. , ...,   0. ,   0. ,   0. ],
        [ 73.2,  73.2,  73.2, ...,  48. ,  49.2,  49.2],
        ...,
        [591. , 591. , 606. , ..., 514.2, 516. , 516. ],
        [493.2, 493.2, 505.8, ..., 436.2, 438. , 438. ],
        [631.2, 631.2, 648. , ..., 559.2, 562.8, 562.8]],

       [[100.8, 100.8, 100.8, ...,  94.8,  94.8,  94.8],
        [ 55.2,  55.2,  55.2, ...,  51. ,  49.8,  49.8],
        [  0. ,   0. ,   0. , ...,   0. ,   0. ,   0. ],
        ...,
        [529.2, 529.2, 541.8, ..., 465. , 466.2, 466.2],
        [429. , 429. , 445.8, ..., 388.2, 388

In [22]:
ff= np.load('data_line_2_6/travel_time_matrix.npy')

In [23]:
ff

array([[[  0. ,   0. ,   0. , ...,   0. ,   0. ,   0. ],
        [ 43.2,  43.2,  43.2, ...,  36. ,  40.2,  40.2],
        [129. , 129. , 129. , ...,  85.8,  93. ,  93. ],
        ...,
        [189. , 189. , 195. , ..., 157.2, 165. , 165. ],
        [220.2, 220.2, 235.8, ..., 195. , 205.8, 205.8],
        [340.8, 340.8, 349.2, ..., 292.8, 298.8, 298.8]],

       [[ 36. ,  36. ,  36. , ...,  33. ,  31.2,  31.2],
        [  0. ,   0. ,   0. , ...,   0. ,   0. ,   0. ],
        [ 78. ,  78. ,  78. , ...,  49.2,  52.2,  52.2],
        ...,
        [160.8, 160.8, 171. , ..., 127.2, 133.2, 133.2],
        [196.2, 196.2, 208.8, ..., 159. , 166.2, 166.2],
        [262.8, 262.8, 267. , ..., 259.2, 262.2, 262.2]],

       [[100.2, 100.2, 100.2, ...,  85.2,  79.8,  79.8],
        [ 63. ,  63. ,  63. , ...,  51. ,  49.2,  49.2],
        [  0. ,   0. ,   0. , ...,   0. ,   0. ,   0. ],
        ...,
        [100.2, 100.2, 100.2, ...,  76.8,  73.2,  73.2],
        [129. , 129. , 130.2, ..., 115.8, 115

In [24]:
import json

# Read the original matrix_metadata.json
with open('data/matrix_metadata.json', 'r') as f:
    matrix_metadata = json.load(f)

# Create new od_metadata.json
od_metadata = {
    "station_ids": matrix_metadata["station_ids"],
    "n_time_slots": matrix_metadata["num_time_slots"],
    "time_slot_duration_seconds": matrix_metadata["time_slot_duration"] * 60,
    "time_slot_duration_minutes": matrix_metadata["time_slot_duration"],
    "description": "OD matrix for passenger demand",
    "units": "passengers per time slot"
}

# Save as od_metadata.json
with open('data/od_metadata.json', 'w') as f:
    json.dump(od_metadata, f, indent=2)

print("✓ od_metadata.json created")
print(f"✓ Contains {len(od_metadata['station_ids'])} stations")
print(f"✓ Number of time slots: {od_metadata['n_time_slots']}")

✓ od_metadata.json created
✓ Contains 29 stations
✓ Number of time slots: 36
